name: End-to-end Planka Tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Trigger
      run: echo "This job triggers the others"

  planka-docker-cypress-tests:
    needs: trigger-job
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        volumes:
          - db-data:/var/lib/postgresql/data
        env:
          POSTGRES_DB: planka
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      planka:
        image: ghcr.io/plankanban/planka:latest
        volumes:
          - user-avatars:/app/public/user-avatars
          - project-background-images:/app/public/project-background-images
          - attachments:/app/private/attachments
        ports:
          - 3000:1337
        env:
          BASE_URL: http://localhost:3000
          DATABASE_URL: postgresql://postgres@postgres/planka
          DEFAULT_ADMIN_EMAIL: cypress@example.com
          DEFAULT_ADMIN_PASSWORD: E2E_test
          DEFAULT_ADMIN_NAME: Cypress Test
          DEFAULT_ADMIN_USERNAME: cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --env api_server=http://localhost:3000

  planka-app-build-and-cypress-tests:
    needs: trigger-job
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        volumes:
          - db-data:/var/lib/postgresql/data
        env:
          POSTGRES_DB: planka
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          cd client
          npm run build

      - name: Setup server
        run: |
            client/tests/setup-symlinks.sh
            cd server
            cp .env.sample .env
            npm run db:init
            cd -
            npm start &

      - name: Wait for development server
        run: |
          sudo apt-get install wait-for-it -y
          wait-for-it -h localhost -p 1337 -t 10

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --env api_server=http://localhost:1337
